apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-token
  namespace: default
spec:
  secretStoreRef:
    name: aws-secretmanager-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: vault-token
    namespace: external-secrets
  data:
    - secretKey: token
      remoteRef:
        key: /production/mgmt/vault/vault_root_token

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-parameterstore-secret
  namespace: external-secrets
spec:
  secretStoreRef:
    name: ps-cluster-default-secretstore  #  SecretStore name
    kind: ClusterSecretStore
  target:
    name: aws-parameterstore-secret  #  name of the Kubernetes secret to create
  data:
    - secretKey: my-parameter-secret  #  key within the Kubernetes secret
      remoteRef:
        key: /my/parameter  # The AWS Parameter Store key to be used as kubernes secret value

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockersecret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: ps-cluster-default-secretstore
    kind: ClusterSecretStore
  target:
    name: dockersecret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: /app/argocd/dockersecret
